/** ISO 3166-1 alpha-2 for flagcdn.com */
export const NATION_FLAG_CODE: Record<string, string> = {
  canada: 'ca',
  mexico: 'mx',
  usa: 'us',
  australia: 'au',
  iraq: 'iq',
  iran: 'ir',
  japan: 'jp',
  jordan: 'jo',
  korea: 'kr',
  qatar: 'qa',
  saudi: 'sa',
  uzbekistan: 'uz',
  algeria: 'dz',
  'cabo-verde': 'cv',
  'congo-dr': 'cd',
  'ivory-coast': 'ci',
  egypt: 'eg',
  ghana: 'gh',
  morocco: 'ma',
  senegal: 'sn',
  'south-africa': 'za',
  tunisia: 'tn',
  curacao: 'cw',
  haiti: 'ht',
  panama: 'pa',
  argentina: 'ar',
  brazil: 'br',
  colombia: 'co',
  ecuador: 'ec',
  paraguay: 'py',
  uruguay: 'uy',
  'new-zealand': 'nz',
  austria: 'at',
  belgium: 'be',
  bosnia: 'ba',
  croatia: 'hr',
  czechia: 'cz',
  england: 'gb-eng',
  france: 'fr',
  germany: 'de',
  netherlands: 'nl',
  norway: 'no',
  portugal: 'pt',
  scotland: 'gb-sct',
  spain: 'es',
  sweden: 'se',
  switzerland: 'ch',
  turkey: 'tr',
  italy: 'it',
  poland: 'pl',
  ukraine: 'ua',
  denmark: 'dk',
  wales: 'gb-wls',
  serbia: 'rs',
  chile: 'cl',
  peru: 'pe',
  venezuela: 've',
  nigeria: 'ng',
  cameroon: 'cm',
  'costa-rica': 'cr',
  jamaica: 'jm',
  china: 'cn',
  thailand: 'th',
}

export function nationFlagUrl(nationId: string, width = 80): string {
  const code = NATION_FLAG_CODE[nationId] ?? 'un'
  return `https://flagcdn.com/w${width}/${code}.png`
}
